# ! Variable Configuration
@port = 3001
@host = http://localhost:{{port}}
@base = {{host}}/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE3MzA0NjA1NDIsImV4cCI6MTczMDU0Njk0Mn0.qiMy0NGKoFmJCvp0N4NVh6JlMawDR9gyhRbY4wUv9yU

# ! Connection Test
### * Test the connection to the configured host
GET {{host}}

# ! User Endpoints

### * Import all pre-admins
POST {{base}}/user/import-all
Authorization: {{token}}

### * Register new user
POST {{base}}/user/register
Content-Type: application/json

{
  "name": "Ariel do Nascimento",
  "email": "john.doe@gmail.com",
  "cpf": "701.720.974-52",
  "password": "#A1b2c3d4"
}

### * User login
POST {{base}}/user/login
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "#A1b2c3d4"
}

### * Request password reset
POST {{base}}/user/request-reset
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
}

### * Change password in settings
PUT {{base}}/user/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "oldPassword": "", 
  "newPassword": ""
}

### * User logout
POST {{base}}/user/logout
Content-Type: application/json
Authorization: {{token}}

### * Delete user account
DELETE {{base}}/user/
Content-Type: application/json
Authorization: {{token}}

# ! Other Endpoints

### * Process PDF
POST {{base}}/upload-pdf
Content-Type: application/json
Authorization: {{token}}

### * 
GET {{base}}/user/
Content-Type: application/json
Authorization: {{token}}