# ! Variable Configuration
@port = 3001
@host = http://localhost:{{port}}
@base = {{host}}/api

# ! Connection Test
### * Test the connection to the configured host
GET {{host}}

# ! User Endpoints

### * Import all pre-admins
POST {{base}}/user/import-all

### * Register new user
POST {{base}}/user/register
Content-Type: application/json

{
  "name": "Ariel do Nascimento",
  "email": "hayadav160@rustetic.com",
  "cpf": "893.266.020-44",
  "password": "#A1b2c3d4",
  "phone": "(83) 9 9234-5235"
}

### * User login
POST {{base}}/user/login
Content-Type: application/json

{
  "email": "hayadav160@rustetic.com",
  "password": "#A1b2c3d4"
}

### * Request password reset
POST {{base}}/user/request-reset
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
}

### * Change password in settings
PUT {{base}}/user/change-password
Content-Type: application/json

{
  "oldPassword": "", 
  "newPassword": ""
}

### * User logout
POST {{base}}/user/logout
Content-Type: application/json

### * Delete user account
DELETE {{base}}/user/
Content-Type: application/json

# ! Other Endpoints

### * Process PDF
POST {{base}}/upload-pdf
Content-Type: application/json

### * 
GET {{base}}/user/
Content-Type: application/json