import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import StyledComponentsRegistry from "@/components/containers/registry";
import "@style/index.scss";
import "normalize.css";
import { ToastContainer } from "react-toastify";
import ReduxProvider from '@provider/ReduxProvider'; 
import "react-toastify/dist/ReactToastify.css";
import { loadEnvConfig } from '@next/env';

const projectDir = process.cwd();
loadEnvConfig(projectDir);
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Medfy Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={inter.className}>
        {<React.StrictMode>
        <ReduxProvider>
          <StyledComponentsRegistry>
            {children}
            <ToastContainer />
          </StyledComponentsRegistry>
        </ReduxProvider>
        </React.StrictMode>}
      </body>
    </html>
  );
}
